# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cryptixwalletd_pb2 as cryptixwalletd__pb2


class cryptixwalletdStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/GetBalance',
                request_serializer=cryptixwalletd__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.GetBalanceResponse.FromString,
                )
        self.GetExternalSpendableUTXOs = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/GetExternalSpendableUTXOs',
                request_serializer=cryptixwalletd__pb2.GetExternalSpendableUTXOsRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.GetExternalSpendableUTXOsResponse.FromString,
                )
        self.CreateUnsignedTransactions = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/CreateUnsignedTransactions',
                request_serializer=cryptixwalletd__pb2.CreateUnsignedTransactionsRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.CreateUnsignedTransactionsResponse.FromString,
                )
        self.ShowAddresses = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/ShowAddresses',
                request_serializer=cryptixwalletd__pb2.ShowAddressesRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.ShowAddressesResponse.FromString,
                )
        self.NewAddress = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/NewAddress',
                request_serializer=cryptixwalletd__pb2.NewAddressRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.NewAddressResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/Shutdown',
                request_serializer=cryptixwalletd__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.ShutdownResponse.FromString,
                )
        self.Broadcast = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/Broadcast',
                request_serializer=cryptixwalletd__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.BroadcastResponse.FromString,
                )
        self.BroadcastReplacement = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/BroadcastReplacement',
                request_serializer=cryptixwalletd__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.BroadcastResponse.FromString,
                )
        self.Send = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/Send',
                request_serializer=cryptixwalletd__pb2.SendRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.SendResponse.FromString,
                )
        self.Sign = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/Sign',
                request_serializer=cryptixwalletd__pb2.SignRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.SignResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/GetVersion',
                request_serializer=cryptixwalletd__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.GetVersionResponse.FromString,
                )
        self.BumpFee = channel.unary_unary(
                '/cryptixwalletd.cryptixwalletd/BumpFee',
                request_serializer=cryptixwalletd__pb2.BumpFeeRequest.SerializeToString,
                response_deserializer=cryptixwalletd__pb2.BumpFeeResponse.FromString,
                )


class cryptixwalletdServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExternalSpendableUTXOs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUnsignedTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAddresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastReplacement(self, request, context):
        """BroadcastReplacement assumes that all transactions depend on the first one
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Since SendRequest contains a password - this command should only be used on
        a trusted or secure connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Since SignRequest contains a password - this command should only be used on
        a trusted or secure connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BumpFee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cryptixwalletdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=cryptixwalletd__pb2.GetBalanceRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.GetBalanceResponse.SerializeToString,
            ),
            'GetExternalSpendableUTXOs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExternalSpendableUTXOs,
                    request_deserializer=cryptixwalletd__pb2.GetExternalSpendableUTXOsRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.GetExternalSpendableUTXOsResponse.SerializeToString,
            ),
            'CreateUnsignedTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUnsignedTransactions,
                    request_deserializer=cryptixwalletd__pb2.CreateUnsignedTransactionsRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.CreateUnsignedTransactionsResponse.SerializeToString,
            ),
            'ShowAddresses': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAddresses,
                    request_deserializer=cryptixwalletd__pb2.ShowAddressesRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.ShowAddressesResponse.SerializeToString,
            ),
            'NewAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAddress,
                    request_deserializer=cryptixwalletd__pb2.NewAddressRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.NewAddressResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=cryptixwalletd__pb2.ShutdownRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.ShutdownResponse.SerializeToString,
            ),
            'Broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.Broadcast,
                    request_deserializer=cryptixwalletd__pb2.BroadcastRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.BroadcastResponse.SerializeToString,
            ),
            'BroadcastReplacement': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastReplacement,
                    request_deserializer=cryptixwalletd__pb2.BroadcastRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.BroadcastResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=cryptixwalletd__pb2.SendRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.SendResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=cryptixwalletd__pb2.SignRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.SignResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=cryptixwalletd__pb2.GetVersionRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.GetVersionResponse.SerializeToString,
            ),
            'BumpFee': grpc.unary_unary_rpc_method_handler(
                    servicer.BumpFee,
                    request_deserializer=cryptixwalletd__pb2.BumpFeeRequest.FromString,
                    response_serializer=cryptixwalletd__pb2.BumpFeeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryptixwalletd.cryptixwalletd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cryptixwalletd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/GetBalance',
            cryptixwalletd__pb2.GetBalanceRequest.SerializeToString,
            cryptixwalletd__pb2.GetBalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExternalSpendableUTXOs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/GetExternalSpendableUTXOs',
            cryptixwalletd__pb2.GetExternalSpendableUTXOsRequest.SerializeToString,
            cryptixwalletd__pb2.GetExternalSpendableUTXOsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUnsignedTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/CreateUnsignedTransactions',
            cryptixwalletd__pb2.CreateUnsignedTransactionsRequest.SerializeToString,
            cryptixwalletd__pb2.CreateUnsignedTransactionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShowAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/ShowAddresses',
            cryptixwalletd__pb2.ShowAddressesRequest.SerializeToString,
            cryptixwalletd__pb2.ShowAddressesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/NewAddress',
            cryptixwalletd__pb2.NewAddressRequest.SerializeToString,
            cryptixwalletd__pb2.NewAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/Shutdown',
            cryptixwalletd__pb2.ShutdownRequest.SerializeToString,
            cryptixwalletd__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/Broadcast',
            cryptixwalletd__pb2.BroadcastRequest.SerializeToString,
            cryptixwalletd__pb2.BroadcastResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BroadcastReplacement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/BroadcastReplacement',
            cryptixwalletd__pb2.BroadcastRequest.SerializeToString,
            cryptixwalletd__pb2.BroadcastResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/Send',
            cryptixwalletd__pb2.SendRequest.SerializeToString,
            cryptixwalletd__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/Sign',
            cryptixwalletd__pb2.SignRequest.SerializeToString,
            cryptixwalletd__pb2.SignResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/GetVersion',
            cryptixwalletd__pb2.GetVersionRequest.SerializeToString,
            cryptixwalletd__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BumpFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptixwalletd.cryptixwalletd/BumpFee',
            cryptixwalletd__pb2.BumpFeeRequest.SerializeToString,
            cryptixwalletd__pb2.BumpFeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
